# vim:set ft=tmux:
%hidden MODULE_NAME="language"

set -gq "@catppuccin_${MODULE_NAME}_icon" "󰌐 "
set -gqF "@catppuccin_${MODULE_NAME}_color" "#{E:@thm_lavender}"
set -gq "@catppuccin_${MODULE_NAME}_text" " #(~/.config/waybar/scripts/language.sh)"

source -F "/home/artyom/.config/tmux/plugins/tmux/utils/status_module.conf"
